name: "package-version"
description: "Extracts version from package.json to an environment variable"
branding:
  color: gray-dark
  icon: package
author: "Dominic Tylor"
inputs:
  path:
    description: "package.json location"
    required: false
  follow-symlinks:
    description: "Indicates whether to follow symbolic links"
    required: false
    default: "true"
outputs:
  next-version: # next version
    description: 'Next version by package flow'
runs:
  using: "node12"
  main: "dist/index.js"
